# Generated by Django 5.0.7 on 2024-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dokumen/')),
                ('tanggal_upload', models.DateField(auto_now_add=True)),
                ('tanggal_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dokumen',
                'verbose_name_plural': 'dokumen',
            },
        ),
        migrations.CreateModel(
            name='proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=255, verbose_name='Nama Proyek')),
                ('nama_paket_pekerjaan', models.CharField(max_length=255, verbose_name='Nama Paket Pekerjaan')),
                ('sub_bidang_pekerjaan', models.CharField(max_length=255, verbose_name='Sub Bidang Pekerjaan')),
                ('peruntukan_bangunan', models.CharField(max_length=255, verbose_name='Peruntukan Bangunan')),
                ('total_volume_atau_area', models.CharField(max_length=255, verbose_name='Total Volume atau Area')),
                ('lokasi_proyek', models.CharField(max_length=255, verbose_name='Lokasi Proyek')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('target_selesai', models.DateField(verbose_name='Target Selesai')),
                ('nama_client', models.CharField(max_length=255, verbose_name='Nama Client')),
                ('no_kontrak', models.CharField(max_length=255, verbose_name='Nomor Kontrak')),
                ('nilai_kontrak', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nilai Kontrak')),
                ('rencana_progress', models.IntegerField(verbose_name='Rencana Progress (%)')),
                ('actual_progress', models.IntegerField(verbose_name='Actual Progress (%)')),
                ('tanggal_update', models.DateField(auto_now=True, verbose_name='Tanggal Update')),
            ],
            options={
                'verbose_name': 'proyek',
                'verbose_name_plural': 'proyek',
            },
        ),
    ]
