# Generated by Django 5.0.7 on 2024-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dokumen/')),
                ('tanggal_upload', models.DateField(auto_now_add=True)),
                ('tanggal_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dokumen',
                'verbose_name_plural': 'dokumen',
            },
        ),
        migrations.CreateModel(
            name='proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket_pekerjaan', models.CharField(max_length=255, verbose_name='Nama Paket Pekerjaan')),
                ('sub_bidang_pekerjaan', models.CharField(max_length=255, verbose_name='Sub Bidang Pekerjaan')),
                ('peruntukan_bangunan', models.CharField(max_length=255, verbose_name='Peruntukan Bangunan')),
                ('total_volume_atau_area', models.CharField(max_length=255, verbose_name='Total Volume atau Area')),
                ('lokasi', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('PJ_atau_PBK_nama', models.CharField(max_length=255, verbose_name='Nama PJ atau PBK')),
                ('PJ_atau_PBK_alamat_telp', models.CharField(max_length=255, verbose_name='Alamat dan Telepon PJ atau PBK')),
                ('kontrak_no_tgl', models.CharField(max_length=255, verbose_name='Nomor dan Tanggal Kontrak')),
                ('kontrak_nilai', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nilai Kontrak')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('tanggal_update', models.DateField(auto_now=True, verbose_name='Tanggal Update')),
                ('sp_kontrak', models.IntegerField(verbose_name='Status Progress Kontrak (%)')),
                ('sp_prestasi_kerja', models.IntegerField(verbose_name='Status Progress Prestasi Kerja (%)')),
            ],
            options={
                'verbose_name': 'proyek',
                'verbose_name_plural': 'proyek',
            },
        ),
    ]
