# Generated by Django 5.0.7 on 2024-10-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumen',
            options={'verbose_name': 'dokumen', 'verbose_name_plural': 'dokumen'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'progress', 'verbose_name_plural': 'progress'},
        ),
        migrations.AlterModelOptions(
            name='proyek',
            options={'verbose_name': 'proyek', 'verbose_name_plural': 'proyek'},
        ),
        migrations.AddField(
            model_name='progress',
            name='dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_set', to='managemen.dokumen'),
        ),
        migrations.AddField(
            model_name='progress',
            name='proyek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_set', to='managemen.proyek'),
        ),
    ]
