# Generated by Django 5.0.7 on 2024-10-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managemen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyek',
            old_name='PJ_atau_PBK_alamat_telp',
            new_name='PJ_atau_PPK_alamat_telp',
        ),
        migrations.RenameField(
            model_name='proyek',
            old_name='PJ_atau_PBK_nama',
            new_name='PJ_atau_PPK_nama',
        ),
    ]
