# Generated by Django 5.0.7 on 2024-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemen', '0002_alter_dokumen_options_alter_progress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='tanggal_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
