# Generated by Django 5.0.7 on 2024-10-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemen', '0003_alter_progress_tanggal_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='selected_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_dokumen', to='managemen.progress'),
        ),
        migrations.AddField(
            model_name='proyek',
            name='selected_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_proyek', to='managemen.progress'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(upload_to='static/dokumen/'),
        ),
    ]
